---
version: 2

models:
  - name: stg_movies
    columns:
      - name: imdb_id
        data_tests:
          - not_null
          - unique
      - name: rating_key
        data_tests:
          - not_null
          - unique
      - name: video_resolution
        data_tests:
          - accepted_values:
              arguments:
                values: ["sd", "480", "576", "720", "1080", "4k"]
      - name: hdr_formats
        data_tests:
          - not_null
      - name: source_platform
        data_tests:
          - accepted_values:
              arguments:
                values: ["Netflix", "Disney+"]
